name: crud_admin

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  webview_flutter: ^4.8.0


flutter:
  uses-material-design: true

  assets:
    - assets/html/
    - assets/images/

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
